services:
  mysql:
    image: mysql:8.0
    container_name: leoni-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leoni_db
    
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: leoni-backend
    depends_on:
      - mysql
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: leoni_db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: leoni-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:80"

volumes:
  mysql_data:
